version: '2'

services:

  coreframework:
    build: CoreFramework/
    environment:
      ASPNETCORE_URLS: "http://+:80"
    networks:
      - network

  elasticsearch:
    build: ELK/elasticsearch/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.zen.ping.unicast.hosts: elasticsearch
      cluster.name: "ES-Cluster"
    networks:
      - network

  logstash:
    build: ELK/logstash/
    volumes:
      - ./ELK/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - network
    depends_on:
      - elasticsearch

  kibana:
    build: ELK/kibana/
    networks:
      - network
    depends_on:
      - elasticsearch

  haproxy:
    build: HAProxy/
    ports:
      - "80:80"
      - "5601:5601"
    networks:
      - network
    depends_on:
      - coreframework
      - kibana
   
networks:
  network:
    driver: bridge