version: '2'

services:

  coreframework:
    build: CoreFramework/
    environment:
      ASPNETCORE_URLS: "http://+:80"
    networks:
      - network

  elasticsearch:
    build: ELK/elasticsearch/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.zen.ping.unicast.hosts: elasticsearch
      cluster.name: "ES-Cluster"
    networks:
      - network

  logstash:
    build: ELK/logstash/
    volumes:
      - ./ELK/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - network
    depends_on:
      - elasticsearch

  kibana:
    build: ELK/kibana/
    networks:
      - network
    depends_on:
      - elasticsearch

  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - coreframework
    environment:
      - KIBANA_DOMAIN="kibana.example.com"
      - APP_DOMAIN="example.com"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./Nginx/conf.d/default.template:/etc/nginx/conf.d/default.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  network:
    driver: bridge